import { ProviderModel } from "../models/Provider.js";
import { RepoModel } from "../models/Repo.js";
import { GithubSettingsModel } from "../models/GithubSettings.js";
import { ChangeModel } from "../models/Change.js";
import { PullRequestModel } from "../models/PullRequest.js";
import { autoScanRepo, applyApprovedFindings } from "../services/autoComplianceScanService.js";
import { createPullRequest } from "../services/githubApiService.js";
import { fetchDocsText } from "../services/docScraperService.js";

export async function runAutoScan(req, res) {
  const { providerId, repoId, branch } = req.body;

  const provider = await ProviderModel.findById(providerId);
  if (!provider) return res.status(404).json({ error: "Provider not found" });

  const repo = await RepoModel.findById(repoId);
  if (!repo || repo.provider_id !== providerId) return res.status(400).json({ error: "Repo not linked to this provider" });
  if (!repo.repo_url) return res.status(400).json({ error: "This repo has no GitHub URL." });

  const settings = await GithubSettingsModel.get();
  if (!settings) return res.status(400).json({ error: "Connect a GitHub account in Settings first." });

  const allChanges = await ChangeModel.findAll({});
  const providerChanges = allChanges.filter((c) =>
    c.provider_id === providerId && c.detection_source !== "repo_scan" && !c.title.startsWith("Compatibility review:")
  );
  let providerContext = "";
  const sourceUrl = provider.changelog_url || provider.docs_url;
  if (sourceUrl) {
    try {
      providerContext = (await fetchDocsText(sourceUrl)).text;
    } catch (err) {
      console.error(`Provider context fetch failed for ${sourceUrl}:`, err.message);
    }
  }

  const result = await autoScanRepo({
    repoUrl: repo.repo_url, token: settings.token,
      branch: branch || repo.default_branch, providerName: provider.name,
        knownChanges: providerChanges, providerContext, requestApiKey: req.geminiApiKey,
  });

  const persistedFindings = [];
  for (const finding of result.findings || []) {
    const change = await ChangeModel.recordScanFinding({
      providerId,
      title: finding.relatedChangeTitle || `Compatibility review: ${finding.file}`,
      description: finding.explanation,
      severity: finding.reviewOnly ? "high" : "medium",
      type: finding.reviewOnly ? "deprecation" : "breaking",
      repoName: repo.repo_name,
      file: finding.file,
    });
    persistedFindings.push({ ...finding, changeId: change.id });
  }

  res.status(200).json({ ...result, findings: persistedFindings });
}

export async function commitApprovedFindings(req, res) {
  const { repoId, branch, mode = "pr", newBranchName, commitMessage, approvedFiles } = req.body;

  if (!Array.isArray(approvedFiles) || approvedFiles.length === 0) {
    return res.status(400).json({ error: "approvedFiles is required and must be non-empty." });
  }
  if (mode === "pr" && !newBranchName) return res.status(400).json({ error: "newBranchName is required when mode is \"pr\"." });

  const repo = await RepoModel.findById(repoId);
  if (!repo || !repo.repo_url) return res.status(400).json({ error: "Repo not found or has no GitHub URL." });

  const settings = await GithubSettingsModel.get();
  if (!settings) return res.status(400).json({ error: "Connect a GitHub account in Settings first." });

  const message = commitMessage || `fix: apply ${approvedFiles.length} auto-detected API compatibility fix(es)`;
  const createNewBranch = mode === "pr";

  const { writtenFiles, pushBranch } = await applyApprovedFindings({
    repoUrl: repo.repo_url, token: settings.token, branch: branch || repo.default_branch,
    createNewBranch, newBranchName, commitMessage: message, approvedFiles,
  });

  let prRecordData = {
    changeId: null,
    repo: repo.repo_name,
    title: message,
    branch: pushBranch,
    baseBranch: branch || repo.default_branch,
    filesChanged: writtenFiles.length,
    diff: writtenFiles.map((f) => `✅ modified: ${f}`).join("\n"),
    prNumber: null,
    prUrl: null,
    status: "committed",
    fixMode: "ai",
  };

  if (createNewBranch) {
    const prBody = ["Automated fix generated by APISentry's AI compliance scan.", "", "### Files changed", ...writtenFiles.map((f) => `- \`${f}\``)].join("\n");
    const ghPR = await createPullRequest(settings.token, repo.repo_url, {
      head: pushBranch, base: branch || repo.default_branch, title: message.slice(0, 250), body: prBody,
    });
    prRecordData = { ...prRecordData, title: ghPR.title, prNumber: ghPR.number, prUrl: ghPR.html_url, status: "open" };
  }

  const pr = await PullRequestModel.create(prRecordData);

  const relatedChangeIds = [...new Set(approvedFiles.map((f) => f.relatedChangeId).filter(Boolean))];
  for (const changeId of relatedChangeIds) {
    await ChangeModel.markStatus(changeId, createNewBranch ? "pr_created" : "committed").catch(() => {});
  }

  res.status(201).json(pr);
}