import { ChangeModel } from "../models/Change.js";
import { PullRequestModel } from "../models/PullRequest.js";
import { RepoModel } from "../models/Repo.js";
import { GithubSettingsModel } from "../models/GithubSettings.js";
import { cloneApplyCommitPush } from "../services/gitService.js";
import { applyCodemods } from "../services/codemodService.js";
import { applyAiFixes } from "../services/aiCodemodService.js";
import { createPullRequest } from "../services/githubApiService.js";

export async function listChanges(req, res) {
  const { type } = req.query;
  res.json(await ChangeModel.findAll({ type }));
}

export async function getChange(req, res) {
  const change = await ChangeModel.findById(req.params.id);
  if (!change) return res.status(404).json({ error: "Change not found" });
  res.json(change);
}

export async function generatePR(req, res) {
  const { id } = req.params;
  const {
    repoId, mode = "pr", baseBranch, newBranchName, commitMessage,
    fixMode = "manual", codemods, filePaths,
  } = req.body;

  if (!repoId) return res.status(400).json({ error: "repoId is required." });
  if (!baseBranch) return res.status(400).json({ error: "baseBranch is required." });
  if (mode === "pr" && !newBranchName) return res.status(400).json({ error: "newBranchName is required when mode is \"pr\"." });
  if (fixMode === "manual" && (!Array.isArray(codemods) || codemods.length === 0)) {
    return res.status(400).json({ error: "At least one codemod is required in manual mode." });
  }
  if (fixMode === "ai" && (!Array.isArray(filePaths) || filePaths.length === 0)) {
    return res.status(400).json({ error: "At least one file path is required in AI mode." });
  }

  const change = await ChangeModel.findById(id);
  if (!change) return res.status(404).json({ error: "Change not found" });

  const repo = await RepoModel.findById(repoId);
  if (!repo || repo.provider_id !== change.provider_id) {
    return res.status(400).json({ error: "That repo isn't linked to this change's provider." });
  }
  if (!repo.repo_url) return res.status(400).json({ error: "This repo has no GitHub URL. Add one from the Providers tab first." });

  const settings = await GithubSettingsModel.get();
  if (!settings) return res.status(400).json({ error: "Connect a GitHub account in Settings before generating a PR." });

  const message = commitMessage || `fix: ${change.title}`;
  const createNewBranch = mode === "pr";

  const applyFn = fixMode === "ai"
    ? (workDir) => applyAiFixes(workDir, change, filePaths, req.geminiApiKey)
    : (workDir) => applyCodemods(workDir, codemods);

  const { results, pushBranch } = await cloneApplyCommitPush({
    repoUrl: repo.repo_url, token: settings.token, baseBranch,
    createNewBranch, newBranchName, commitMessage: message, applyFn,
  });

  const changedResults = results.filter((r) => r.changed);
  const skippedResults = results.filter((r) => !r.changed);

  let prRecordData = {
    changeId: change.id,
    repo: repo.repo_name,
    title: message,
    branch: pushBranch,
    baseBranch,
    filesChanged: changedResults.length,
    diff: [
      ...changedResults.map((r) => `✅ modified: ${r.file}`),
      ...skippedResults.map((r) => `⏭️  skipped: ${r.file} (${r.reason})`),
    ].join("\n"),
    prNumber: null,
    prUrl: null,
    status: "committed",
    fixMode,
  };

  if (createNewBranch) {
    const prBody = [
      `Automated fix for a detected API change from **${change.provider_name}**.`,
      "",
      `**${change.title}**`,
      "",
      change.description,
      "",
      fixMode === "ai" ? "_Fix generated by Gemini — only files it determined needed changes were modified._" : "_Fix applied via manual find/replace._",
      "",
      "### Files",
      ...changedResults.map((r) => `- ✅ \`${r.file}\` — modified`),
      ...skippedResults.map((r) => `- ⏭️ \`${r.file}\` — ${r.reason}`),
    ].join("\n");

    const ghPR = await createPullRequest(settings.token, repo.repo_url, {
      head: pushBranch, base: baseBranch, title: message.slice(0, 250), body: prBody,
    });

    prRecordData = { ...prRecordData, title: ghPR.title, prNumber: ghPR.number, prUrl: ghPR.html_url, status: "open" };
  }

  const pr = await PullRequestModel.create(prRecordData);
  await ChangeModel.markStatus(change.id, createNewBranch ? "pr_created" : "committed");

  res.status(201).json(pr);
}

export async function deleteChange(req, res) {
  const { id } = req.params;
  const change = await ChangeModel.findById(id);
  if (!change) return res.status(404).json({ error: "Change not found" });

  await ChangeModel.delete(id);
  res.status(200).json({ deleted: true, id });
}

export async function ignoreChange(req, res) {
  const change = await ChangeModel.markStatus(req.params.id, "ignored");
  if (!change) return res.status(404).json({ error: "Change not found" });
  res.json(change);
}

export async function deleteAllChanges(req, res) {
  const deleted = await ChangeModel.deleteAll();
  res.json({ deleted });
}